project:
  type: website
  output-dir: docs

website:
  title: "Cool Website."
  navbar:
    left:
      - stuff/item1.qmd
      - stuff/item2.qmd
  drafts:
    - stuff/item2.qmd
  draft-mode: unlinked