project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    right:
      - talks.qmd
      - about.qmd 
      - text: "خانه"
        href: index.qmd
  page-navigation: true
  favicon: images/favicon.ico
format:
  html:
    css: styles.css