project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  # favicon: images/favicon.ico
  title: "آموزش برنامه نویسی پایتون"

  description: "Homepage"
  site-url: "https://haghbinh.github.io/Pylab/"

  repo-url: https://github.com/haghbinh/Pylab

  open-graph: true

  page-footer:
    # right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Hossein Haghbin"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/favicon.ico"
    pinned: true
    align: center
    tools:
          - icon: github
            href: https://github.com/haghbinh
            text: "GitHub organization"
          - icon: code-square
            href: https://cmgr.oit.duke.edu/containers
            text: "RStudio Containers"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: about.qmd
            text: Overview
          - href: about.qmd
            text: Syllabus
          - href: about.qmd
            text: Support
          - href: about.qmd
            text: Teaching team
          - href: about.qmd
            text: Schedule
          - href: about.qmd
            text: Useful links
          - href: about.qmd
            text: FAQ
      - section: "Computing"
        contents:
          - href: about.qmd
            text: Access
          - href: about.qmd
            text: Troubleshooting
      - section: "Project"
        contents:
          - href: about.qmd
            text: Description
          - href: about.qmd
            text: Tips + resources
      - section: "Weekly materials"
        contents:
          - href: about.qmd
            text: "Week 1"
          - href: about.qmd
            text: "Week 2"
          - href: about.qmd
            text: "Week 3"
          - href: about.qmd
            text: "Week 4"
      - section: "Supplemental notes"
        contents:
          - href: about.qmd
            text: SLR derivations
format:
  html:
    # theme: spacelab
    # css: styles.css
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    lang: fa
    direction: rtl

freeze: auto

editor: visual

