project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - talks.qmd
      - about.qmd 
  page-navigation: true

format:
  html:
    theme: flatly
    css: styles.css